"""empty message

Revision ID: 970c7143c80d
Revises: 
Create Date: 2019-03-11 22:26:43.052129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970c7143c80d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('end_time', sa.String(length=80), nullable=True))
    op.add_column('class', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('class', sa.Column('start_time', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'start_time')
    op.drop_column('class', 'location')
    op.drop_column('class', 'end_time')
    # ### end Alembic commands ###
